repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
      - id: flake8
  - repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
