dist: xenial
language: python
python:
  - "2.7"
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache: pip
install:
  - make virtualenv install-requirements download-corpora download-spacy-data-en
script: make test
after_script: cd ~
addons:
  apt:
    packages:
      - python2.7-dev
      - libxml2-dev
      - libxslt1-dev
      - libpng-dev
      - libfreetype6-dev
      - graphviz
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
